### ISSUE TITLE
How is this possibly supposed to work on an arduino?

### ISSUE THREAD

**Issue by captainwasabi** [guglielmino/arduino-pushetta-lib#4]
No filesystem, no command line, no curl, etc.  Maybe I misunderstand.

**Comment by guglielmino** [comment]
Can you give me more details about how you tried Pushetta? I can't give you any hints without knowing what kind of problem are you facing

**Comment by captainwasabi** [comment]
Installed it to platformio via library manger.  Tried to build, cant find
process.h. Hopped over to github to look at what your doing and you are
creating bash shell scripts on the fly and executing them.  This isn't
going to work on an Uno or the NodeMCU ESP8266 I'm currently working with.
I think the lib is just categorized incorrectly on the platformIO site,
this will only work with boards that are running unix.  (might still use it
on my rPi)

##

**Comment by captainwasabi** [comment]
Ah, ok, this is designed specifically for the Yun, which does run linux.  My bad (but it should probably say something about that in the description on the platformIO site.)
